### PR TITLE
Fix array detection bug in builder

### LINKED ISSUE #21: RelayBuilder does not allow iterators to be used
The current [array check in `RelayBuilder`](https://github.com/relayphp/Relay.Relay/blob/277638ddafe184550d9c2441c23dd911d605a5ce/src/RelayBuilder.php#L94-L105) is not robust and will fail for any number of other iterator types, such as classes that implement `Iterator` but do not use `ArrayObject`.

### PR DESCRIPTION
**Pull request by shadowhand**
The correct way to detect for objects that can be used as iterators is
against the `Traversable` interface. This works for `ArrayObject` and
any other objects that implement iterator interfaces.

http://php.net/traversable

Fixes #21

### CODE REVIEW

**Comment by shadowhand** [comment]
@pmjones having this merged and tagged ASAP would be really helpful to us. We're trying to refactor our middleware handling and this is a blocker.

**Comment by shadowhand** [comment]
@pmjones I choose to leave `GetArrayCopyInterface` intact because I didn't want to break BC. I have no idea why that interface exists though.

**Comment by pmjones** [comment]
Again, my guess is that it's a _subtle_ BC break. E.g., objects extending ArrayObject will now be passed through `iterator_to_array()` instead of calling `getArrayCopy()` on them. I find it easy to imagine that may have unintended consequences.

If this is going to go into 1.x, I think the existing ArrayObject and GetArrayCopyInterface has to be left alone, and adding Traversable checks _only if_ the `$queue` is not one of those already.

Hope that makes sense.

**Comment by pmjones** [comment]
Having said that, since 2.x is not stable (or even released) making that kind of change is super-easy.

**Comment by shadowhand** [comment]
@pmjones I will update the PR to continue to use `getArrayCopy` so that this can be released in 1.0 and I will make a separate PR for 2.0 that removes `GetArrayCopyInterface` and uses `iterator_to_array` for all `Traversable`.

**Comment by pmjones** [comment]
Good deal, and thanks.

File: src/RelayBuilder.php [hunk 1]
```diff
@@ -95,13 +96,16 @@ protected function getArray($queue)
             return $queue;
         }
 
-        $getArrayCopy = $queue instanceof GetArrayCopyInterface
-            || $queue instanceof ArrayObject;
-
-        if ($getArrayCopy) {
+        if ($queue instanceof ArrayObject
+            || $queue instanceof GetArrayCopyInterface
```
Comment (shadowhand) [inline src/RelayBuilder.php]: @pmjones restored the check for `ArrayObject` and ...

File: tests/RelayBuilderTest.php [hunk 2]
```diff
@@ -25,6 +26,15 @@ public function testArrayObject()
         $queue = new ArrayObject([]);
         $relay = $this->relayBuilder->newInstance($queue);
         $this->assertInstanceOf('Relay\Relay', $relay);
+
+        $queue = $this->getMock(ArrayObject::class);
+        $queue
+            ->expects($this->once())
+            ->method('getArrayCopy')
+            ->willReturn([]);
```
Comment (shadowhand) [inline tests/RelayBuilderTest.php:34]: ... tested that `ArrayObject::getArrayCopy` will always be used.

File: tests/RelayBuilderTest.php [hunk 3]
```diff
@@ -34,6 +44,14 @@ public function testGetArrayCopyInterface()
         $this->assertInstanceOf('Relay\Relay', $relay);
     }
 
+    public function testTraversable()
+    {
+        $queue = $this->getMock(Traversable::class);
+
+        $relay = $this->relayBuilder->newInstance($queue);
+        $this->assertInstanceOf('Relay\Relay', $relay);
```
Comment (shadowhand) [inline tests/RelayBuilderTest.php:52]: Also added test for `Traversable` hint.

**Comment by shadowhand** [comment]
I will make the second PR once this merged into 1.x and 1.x is merged into 2.x.

File: src/RelayBuilder.php (hunk 1 above)
Comment (pmjones) [inline src/RelayBuilder.php]: Man, I don't mean to be a nitpicker, but can you restore those lines to exactly as they were? If nothing else it makes the diff cleaner. Thanks for your patience with my OCD.

Comment (shadowhand) [inline src/RelayBuilder.php]: Done.

**Comment by pmjones** [comment]
That test is gorgeous. Waiting for CI to run then will merge.

**Comment by shadowhand** [comment]
:smile:

**Comment by shadowhand** [comment]
@pmjones excellent! Will you tag that and merge 1.x into 2.x so I can finish the second part?

**Comment by pmjones** [comment]
Yes, will do so shortly. Need to update the README and take care of a couple other release-related administrative tasks.

**Comment by shadowhand** [comment]
:+1:

**Comment by pmjones** [comment]
Done: https://github.com/relayphp/Relay.Relay/releases/tag/1.1.0
